#!/usr/bin/env python3
"""
Claudio - Interactive Installer
Wizard de instalacion con preguntas interactivas
"""

import os
import sys
import json
import shutil
from pathlib import Path

# Colores para terminal
class Colors:
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    BLUE = '\033[94m'
    MAGENTA = '\033[95m'
    END = '\033[0m'
    BOLD = '\033[1m'

def print_header(text):
    print(f"\n{Colors.CYAN}{Colors.BOLD}{'=' * 70}{Colors.END}")
    print(f"{Colors.CYAN}{Colors.BOLD}{text.center(70)}{Colors.END}")
    print(f"{Colors.CYAN}{Colors.BOLD}{'=' * 70}{Colors.END}\n")

def print_section(text):
    print(f"\n{Colors.YELLOW}{Colors.BOLD}>>> {text}{Colors.END}\n")

def print_success(text):
    print(f"{Colors.GREEN}✓ {text}{Colors.END}")

def print_error(text):
    print(f"{Colors.RED}✗ {text}{Colors.END}")

def print_info(text):
    print(f"{Colors.BLUE}ℹ {text}{Colors.END}")

def ask_question(question, default=None, password=False, required=True):
    """Hacer una pregunta al usuario"""
    prompt = f"{Colors.MAGENTA}→{Colors.END} {question}"
    if default:
        prompt += f" [{Colors.GREEN}{default}{Colors.END}]"
    prompt += ": "

    if password:
        import getpass
        answer = getpass.getpass(prompt)
    else:
        answer = input(prompt).strip()

    if not answer and default:
        answer = default

    if required and not answer:
        print_error("Este campo es obligatorio")
        return ask_question(question, default, password, required)

    return answer

def ask_choice(question, choices, default=0):
    """Hacer una pregunta con opciones multiples"""
    print(f"\n{Colors.MAGENTA}→{Colors.END} {question}")
    for i, choice in enumerate(choices):
        prefix = f"{Colors.GREEN}[{i+1}]{Colors.END}"
        if i == default:
            prefix += f" {Colors.YELLOW}(default){Colors.END}"
        print(f"    {prefix} {choice}")

    while True:
        prompt = f"{Colors.MAGINA}→{Colors.END} Selecciona una opción [1-{len(choices)}]: "
        answer = input(prompt).strip()

        if not answer:
            return default

        try:
            choice = int(answer) - 1
            if 0 <= choice < len(choices):
                return choice
            print_error(f"Opción inválida. Debe ser entre 1 y {len(choices)}")
        except ValueError:
            print_error("Ingresa un número")

def ask_yes_no(question, default=True):
    """Hacer una pregunta de si/no"""
    default_str = "Y/n" if default else "y/N"
    answer = ask_question(f"{question} ({default_str})", default="Y" if default else "N").lower()

    if not answer:
        return default

    return answer in ['y', 'yes', 's', 'si']

def validate_api_key(key, provider):
    """Validación básica de API key"""
    if not key:
        return False

    if provider == "anthropic":
        return key.startswith("sk-ant-")
    elif provider == "openai":
        return key.startswith("sk-")
    elif provider == "n8n":
        return len(key) > 20

    return len(key) > 10

def create_env_file(config):
    """Crear archivo .env con la configuración"""
    env_content = f"""# Claudio Bot - Configuration File
# Generated by interactive installer

# ============================================
# TELEGRAM CONFIG
# ============================================
TELEGRAM_TOKEN={config['telegram_token']}

# ============================================
# AI PROVIDER CONFIG
# ============================================
AI_PROVIDER={config['ai_provider']}
"""

    # Agregar API key según el proveedor
    if config['ai_provider'] == 'anthropic':
        env_content += f"ANTHROPIC_API_KEY={config['api_key']}\n"
        if config.get('anthropic_model'):
            env_content += f"ANTHROPIC_MODEL={config['anthropic_model']}\n"
    elif config['ai_provider'] == 'openai':
        env_content += f"OPENAI_API_KEY={config['api_key']}\n"
        if config.get('openai_model'):
            env_content += f"OPENAI_MODEL={config['openai_model']}\n"
    elif config['ai_provider'] == 'ollama':
        env_content += f"OLLAMA_BASE_URL={config.get('ollama_url', 'http://localhost:11434')}\n"
        if config.get('ollama_model'):
            env_content += f"OLLAMA_MODEL={config['ollama_model']}\n"

    # n8n config (opcional)
    if config.get('n8n_enabled'):
        env_content += f"""
# ============================================
# N8N CONFIG (optional)
# ============================================
N8N_API_KEY={config.get('n8n_api_key', '')}
N8N_INSTANCE_URL={config.get('n8n_url', 'https://localhost')}
N8N_HOST_HEADER={config.get('n8n_host', 'localhost')}
"""

    # Server config
    port = config.get('port', '8000')
    env_content += f"""
# ============================================
# SERVER CONFIG
# ============================================
CLADIO_PORT={port}
CLADIO_SERVER_URL=http://localhost:{port}
REQUEST_TIMEOUT=60

# ============================================
# SECURITY
# ============================================
# Telegram User ID(s) allowed (comma separated)
# Get your ID from @userinfobot on Telegram
ALLOWED_USERS={config.get('allowed_users', '*')}
"""

    return env_content

def create_systemd_service(config):
    """Crear archivos de servicio systemd para Linux"""
    port = config.get('port', '8000')
    install_dir = config.get('install_dir', '/opt/claudio-bot')

    server_service = f"""[Unit]
Description=Claudio Server
After=network.target

[Service]
Type=simple
User=claudio
WorkingDirectory={install_dir}
EnvironmentFile={install_dir}/.env
ExecStart={install_dir}/venv/bin/python claudio_complete.py
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
"""

    bot_service = f"""[Unit]
Description=Claudio Telegram Bot
After=network.target claudio-server.service

[Service]
Type=simple
User=claudio
WorkingDirectory={install_dir}
EnvironmentFile={install_dir}/.env
ExecStart={install_dir}/venv/bin/python bot_v2.py
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
"""

    return server_service, bot_service

def create_deployment_script(config):
    """Crear script de despliegue para VPS"""
    port = config.get('port', '8000')
    install_dir = config.get('install_dir', '/opt/claudio-bot')

    script = f"""#!/bin/bash
# Claudio - Deploy to VPS
# Generated by installer

set -e

VPS_HOST="{config.get('vps_host', 'your.vps.ip')}"
VPS_USER="{config.get('vps_user', 'ubuntu')}"
PROJECT_DIR="{config.get('project_dir', '~/claudio-bot')}"

echo "======================================================================"
echo "  Deploying Claudio to VPS: $VPS_HOST"
echo "======================================================================"
echo ""

# Paso 1: Copiar archivos
echo "[1/5] Copying files to VPS..."
scp claudio_complete.py $VPS_USER@$VPS_HOST:/tmp/
scp bot_v2.py $VPS_USER@$VPS_HOST:/tmp/
scp n8n_database.py $VPS_USER@$VPS_HOST:/tmp/
scp n8n_mcp_tools.py $VPS_USER@$VPS_HOST:/tmp/
scp requirements.txt $VPS_USER@$VPS_HOST:/tmp/
scp -r skills $VPS_USER@$VPS_HOST:/tmp/
scp .env $VPS_USER@$VPS_HOST:/tmp/

# Paso 2: Crear directorio y usuario
echo "[2/5] Setting up VPS..."
ssh $VPS_USER@$VPS_HOST "sudo useradd -m -s /bin/bash claudio 2>/dev/null || true"
ssh $VPS_USER@$VPS_HOST "sudo mkdir -p {install_dir}"
ssh $VPS_USER@$VPS_HOST "sudo chown -R claudio:claudio {install_dir}"

# Paso 3: Mover archivos
echo "[3/5] Moving files to {install_dir}..."
ssh $VPS_USER@$VPS_HOST "sudo mv /tmp/*.py {install_dir}/"
ssh $VPS_USER@$VPS_HOST "sudo mv /tmp/skills {install_dir}/"
ssh $VPS_USER@$VPS_HOST "sudo mv /tmp/.env {install_dir}/"
ssh $VPS_USER@$VPS_HOST "sudo mv /tmp/requirements.txt {install_dir}/"

# Paso 4: Configurar entorno Python
echo "[4/5] Setting up Python environment..."
ssh $VPS_USER@$VPS_HOST "cd {install_dir} && sudo -u claudio python3 -m venv venv"
ssh $VPS_USER@$VPS_HOST "sudo -u claudio {install_dir}/venv/bin/pip install -q -r {install_dir}/requirements.txt"

# Paso 5: Crear servicios systemd
echo "[5/5] Creating systemd services..."
ssh $VPS_USER@$VPS_HOST "sudo tee /etc/systemd/system/claudio-server.service > /dev/null <<'SVCEOF'
[Unit]
Description=Claudio Server
After=network.target

[Service]
Type=simple
User=claudio
WorkingDirectory={install_dir}
EnvironmentFile={install_dir}/.env
ExecStart={install_dir}/venv/bin/python claudio_complete.py
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
SVCEOF"

ssh $VPS_USER@$VPS_HOST "sudo systemctl daemon-reload"
ssh $VPS_USER@$VPS_HOST "sudo systemctl enable claudio-server.service"
ssh $VPS_USER@$VPS_HOST "sudo systemctl start claudio-server.service"

echo ""
echo "======================================================================"
echo "  Deployment complete!"
echo "======================================================================"
echo ""
echo "Check status: ssh $VPS_USER@$VPS_HOST 'sudo systemctl status claudio-server'"
echo ""
"""
    return script

def main():
    """Función principal del instalador"""
    print_header("CLAUDIO - INTERACTIVE INSTALLER")

    print_info("Bienvenido al instalador de Claudio")
    print_info("Este asistente te guiará paso a paso en la configuración")

    config = {}

    # ============================================
    # PASO 1: Proveedor de IA
    # ============================================
    print_section("PASO 1: Selecciona tu Proveedor de IA")

    ai_providers = [
        "Anthropic (Claude) - Recomendado, mejor calidad",
        "OpenAI (GPT-4/GPT-3.5) - Alternativa popular",
        "Ollama - Local y gratuito (requiere instalación local)",
        "Configurar múltiples proveedores"
    ]

    ai_choice = ask_choice("¿Qué proveedor de IA deseas usar?", ai_providers, default=0)

    if ai_choice == 0:
        config['ai_provider'] = 'anthropic'
        print_info("Has seleccionado Anthropic (Claude)")

        while True:
            api_key = ask_question("Ingresa tu API Key de Anthropic", password=True)
            if validate_api_key(api_key, 'anthropic'):
                config['api_key'] = api_key
                break
            print_error("API Key inválida. Debe comenzar con 'sk-ant-'")

        models = ["claude-sonnet-4-20250514", "claude-3-5-sonnet-20241022", "claude-3-haiku-20240307"]
        model_choice = ask_choice("¿Qué modelo de Claude deseas usar?", models, default=0)
        config['anthropic_model'] = models[model_choice]

    elif ai_choice == 1:
        config['ai_provider'] = 'openai'
        print_info("Has seleccionado OpenAI")

        while True:
            api_key = ask_question("Ingresa tu API Key de OpenAI", password=True)
            if validate_api_key(api_key, 'openai'):
                config['api_key'] = api_key
                break
            print_error("API Key inválida. Debe comenzar con 'sk-'")

        models = ["gpt-4o", "gpt-4-turbo", "gpt-3.5-turbo"]
        model_choice = ask_choice("¿Qué modelo de OpenAI deseas usar?", models, default=0)
        config['openai_model'] = models[model_choice]

    elif ai_choice == 2:
        config['ai_provider'] = 'ollama'
        print_info("Has seleccionado Ollama (local)")

        ollama_url = ask_question("URL de Ollama", default="http://localhost:11434")
        config['ollama_url'] = ollama_url

        models = ["llama3", "llama3:70b", "mistral", "codellama"]
        model_choice = ask_choice("¿Qué modelo de Ollama deseas usar?", models, default=0)
        config['ollama_model'] = models[model_choice]
        config['api_key'] = "not-needed"

    else:
        config['ai_provider'] = 'multi'
        print_info("Configurarás múltiples proveedores")
        # Simplificado para el ejemplo
        anthropic_key = ask_question("API Key de Anthropic (opcional)", default="", password=True, required=False)
        openai_key = ask_question("API Key de OpenAI (opcional)", default="", password=True, required=False)

        if anthropic_key and validate_api_key(anthropic_key, 'anthropic'):
            config['anthropic_api_key'] = anthropic_key
        if openai_key and validate_api_key(openai_key, 'openai'):
            config['openai_api_key'] = openai_key

    # ============================================
    # PASO 2: Configuración de Telegram
    # ============================================
    print_section("PASO 2: Configuración de Telegram")

    print_info("Necesitas un bot de Telegram. Si no tienes uno:")
    print_info("  1. Abre @BotFather en Telegram")
    print_info("  2. Envía /newbot")
    print_info("  3. Sigue las instrucciones")
    print_info("  4. Copia el token que te da")

    while True:
        telegram_token = ask_question("Ingresa el Token de tu Bot de Telegram", password=True)
        if telegram_token and len(telegram_token) > 20:
            config['telegram_token'] = telegram_token
            break
        print_error("Token inválido. Debe ser un token largo de Telegram")

    # ============================================
    # PASO 3: Configuración de n8n (opcional)
    # ============================================
    print_section("PASO 3: Integración con n8n (Opcional)")

    n8n_enabled = ask_yes_no("¿Deseas integrar n8n para gestión de workflows?", default=False)

    if n8n_enabled:
        config['n8n_enabled'] = True
        print_info("Claudio podrá acceder a tu instancia de n8n")

        n8n_url = ask_question("URL de tu instancia n8n", default="https://n8n.aicorebots.com")
        config['n8n_url'] = n8n_url

        n8n_host = ask_question("Header Host (si usas proxy/dominio)", default=n8n_url.replace('https://', '').replace('http://', ''))
        config['n8n_host'] = n8n_host

        n8n_api_key = ask_question("API Key de n8n (opcional)", default="", password=True, required=False)
        config['n8n_api_key'] = n8n_api_key or "no-api-key"
    else:
        config['n8n_enabled'] = False
        config['n8n_url'] = 'https://localhost'
        config['n8n_host'] = 'localhost'
        config['n8n_api_key'] = ''

    # ============================================
    # PASO 4: Configuración del Servidor
    # ============================================
    print_section("PASO 4: Configuración del Servidor")

    deployment_modes = [
        "Local - Ejecutar en tu computadora",
        "VPS - Desplegar en servidor remoto (Linux)",
        "Docker - Usar contenedores Docker"
    ]

    deployment_choice = ask_choice("¿Cómo deseas ejecutar Claudio?", deployment_modes, default=0)

    if deployment_choice == 0:
        config['deployment'] = 'local'
        port = ask_question("Puerto para el servidor local", default="8001")
        config['port'] = port

    elif deployment_choice == 1:
        config['deployment'] = 'vps'
        config['port'] = '8000'

        print_info("Configuración para VPS")

        vps_host = ask_question("IP o dominio de tu VPS", default="51.222.207.250")
        config['vps_host'] = vps_host

        vps_user = ask_question("Usuario SSH", default="ubuntu")
        config['vps_user'] = vps_user

        install_dir = ask_question("Directorio de instalación", default="/opt/claudio-bot")
        config['install_dir'] = install_dir

        project_dir = ask_question("Directorio del proyecto local", default="~/claudio-bot")
        config['project_dir'] = project_dir

    else:
        config['deployment'] = 'docker'
        config['port'] = '8000'

    # ============================================
    # PASO 5: Seguridad
    # ============================================
    print_section("PASO 5: Seguridad")

    print_info("Para restringir el acceso a tu bot:")
    print_info("  1. Abre @userinfobot en Telegram")
    print_info("  2. Envía /start")
    print_info("  3. Copia tu User ID")

    restrict_access = ask_yes_no("¿Deseas restringir el acceso a usuarios específicos?", default=False)

    if restrict_access:
        allowed_users = ask_question("Ingresa los User IDs permitidos (separados por coma)", default="*")
        config['allowed_users'] = allowed_users
    else:
        config['allowed_users'] = '*'

    # ============================================
    # RESUMEN Y CONFIRMACIÓN
    # ============================================
    print_section("RESUMEN DE CONFIGURACIÓN")

    print(f"  Proveedor IA:  {Colors.GREEN}{config['ai_provider'].upper()}{Colors.END}")
    print(f"  Telegram:      {Colors.GREEN}Configurado{Colors.END}")
    print(f"  n8n:           {Colors.GREEN}{'Habilitado' if config.get('n8n_enabled') else 'Deshabilitado'}{Colors.END}")
    print(f"  Despliegue:    {Colors.GREEN}{config['deployment'].upper()}{Colors.END}")
    print(f"  Puerto:        {Colors.GREEN}{config.get('port', 'N/A')}{Colors.END}")
    print(f"  Seguridad:     {Colors.GREEN}{'Restringido' if config.get('allowed_users') != '*' else 'Abierto'}{Colors.END}")

    print()

    if not ask_yes_no("¿Esta configuración es correcta? ¿Continuar?", default=True):
        print_info("Instalación cancelada. Puedes ejecutar el instalador nuevamente.")
        sys.exit(0)

    # ============================================
    # CREAR ARCHIVOS
    # ============================================
    print_section("CREANDO ARCHIVOS DE CONFIGURACIÓN")

    # Crear .env
    env_content = create_env_file(config)
    with open('.env', 'w') as f:
        f.write(env_content)
    print_success("Archivo .env creado")

    # Guardar config para uso futuro
    with open('.claudio_config.json', 'w') as f:
        # Guardar sin valores sensibles
        safe_config = config.copy()
        if 'api_key' in safe_config:
            safe_config['api_key'] = '***HIDDEN***'
        if 'telegram_token' in safe_config:
            safe_config['telegram_token'] = '***HIDDEN***'
        json.dump(safe_config, f, indent=2)
    print_success("Configuración guardada en .claudio_config.json")

    # Crear scripts según el modo de despliegue
    if config['deployment'] == 'vps':
        deploy_script = create_deployment_script(config)
        with open('deploy_vps.sh', 'w') as f:
            f.write(deploy_script)
        os.chmod('deploy_vps.sh', 0o755)
        print_success("Script de despliegue VPS creado: deploy_vps.sh")

        # Crear servicios systemd
        server_svc, bot_svc = create_systemd_service(config)
        with open('claudio-server.service', 'w') as f:
            f.write(server_svc)
        with open('claudio-telegram-bot.service', 'w') as f:
            f.write(bot_svc)
        print_success("Archivos de servicio systemd creados")

    # ============================================
    # INSTALACIÓN
    # ============================================
    print_section("INSTALACIÓN")

    if config['deployment'] == 'local':
        print_info("Instalando dependencias Python...")

        # Verificar si hay venv
        if not os.path.exists('venv'):
            os.system('python3 -m venv venv')
            print_success("Entorno virtual creado")

        # Instalar dependencias
        requirements = []

        # Dependencias base
        requirements.extend([
            'python-telegram-bot==21.0',
            'python-dotenv==1.0.0',
            'fastapi==0.115.0',
            'uvicorn==0.32.0',
            'httpx==0.27.2',
            'pydantic==2.9.2'
        ])

        # Dependencias según proveedor
        if config['ai_provider'] in ['anthropic', 'multi']:
            requirements.append('anthic==0.40.0')

        if config['ai_provider'] in ['openai', 'multi']:
            requirements.append('openai==1.0.0')

        # Crear requirements.txt
        with open('requirements.txt', 'w') as f:
            f.write('\n'.join(requirements))

        # Instalar
        if os.name == 'nt':  # Windows
            print_info("Ejecuta: venv\\Scripts\\pip install -r requirements.txt")
        else:  # Linux/Mac
            os.system('venv/bin/pip install -q -r requirements.txt')
            print_success("Dependencias instaladas")

        # Crear script de inicio
        if os.name == 'nt':
            start_script = """@echo off
title Claudio Bot
echo Starting Claudio Bot...
venv\\Scripts\\python bot_v2.py
pause
"""
            with open('start.bat', 'w') as f:
                f.write(start_script)

            server_script = """@echo off
title Claudio Server
echo Starting Claudio Server...
venv\\Scripts\\python claudio_complete.py
pause
"""
            with open('start_server.bat', 'w') as f:
                f.write(server_script)
        else:
            start_script = """#!/bin/bash
echo "Starting Claudio Bot..."
venv/bin/python bot_v2.py
"""
            with open('start.sh', 'w') as f:
                f.write(start_script)
            os.chmod('start.sh', 0o755)

        print_success("Scripts de inicio creados")

    # ============================================
    # INSTRUCCIONES FINALES
    # ============================================
    print_header("INSTALACIÓN COMPLETADA")

    print()
    print(f"{Colors.BOLD}{Colors.GREEN}¡Claudio está listo para usar!{Colors.END}\n")

    if config['deployment'] == 'local':
        print(f"{Colors.YELLOW}Para iniciar Claudio:{Colors.END}")
        if os.name == 'nt':
            print(f"  1. Doble clic en {Colors.GREEN}start_server.bat{Colors.END} (inicia el servidor)")
            print(f"  2. Doble clic en {Colors.GREEN}start.bat{Colors.END} (inicia el bot)")
        else:
            print(f"  {Colors.GREEN}./start.sh{Colors.END}")

        print()
        print(f"{Colors.YELLOW}Para detener:{Colors.END}")
        print(f"  Presiona {Colors.GREEN}Ctrl+C{Colors.END} en la terminal")

    elif config['deployment'] == 'vps':
        print(f"{Colors.YELLOW}Para desplegar a VPS:{Colors.END}")
        print(f"  {Colors.GREEN}bash deploy_vps.sh{Colors.END}")

        print()
        print(f"{Colors.YELLOW}O manualmente:{Colors.END}")
        print(f"  1. Conecta a tu VPS: ssh {config['vps_user']}@{config['vps_host']}")
        print(f"  2. Copia los archivos")
        print(f"  3. Ejecuta los servicios systemd")

    elif config['deployment'] == 'docker':
        print(f"{Colors.YELLOW}Para usar Docker:{Colors.END}")
        print(f"  {Colors.GREEN}docker-compose up -d{Colors.END}")

    print()
    print(f"{Colors.CYAN}Para verificar el estado:{Colors.END}")
    print(f"  {Colors.GREEN}curl http://localhost:{config.get('port', '8000')}/health{Colors.END}")

    print()
    print(f"{Colors.CYAN}Únete a tu bot en Telegram y comienza a chatear!{Colors.END}")
    print()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print()
        print_error("Instalación cancelada por el usuario")
        sys.exit(0)
    except Exception as e:
        print()
        print_error(f"Error durante la instalación: {e}")
        sys.exit(1)
